### ISSUE TITLE
Doesnt work in module

### ISSUE THREAD

**Issue by crudi** [wojsmol/backbutton-plugin#1]
Any chance to get it to work in a module? If I great a custom module it only shows the string brackets. In content it works fine.

**Comment by wojsmol** [comment]
Hello
Please describe the problem in more detail. A moment ago I tested for proper operation by specifying {backbutton} in the content of Custom HTML module. everything works if in the module on the Options tab "Prepare Content" is set to "yes"
Greetings

**Comment by wojsmol** [comment]
@crudi Please comment whether the problem still occurs.

**Comment by crudi** [comment]
Sorry - we just moved into a house and I have internet now for the first time. "Prepare content" solved the problem.... works fine - thank you.

**Comment by wojsmol** [comment]
OK, no problem:)

PS: Please post a review for Back Button at the Joomla! Extensions Directory http://extensions.joomla.org/extensions/extension/structure-a-navigation/site-navigation/back-button

**Comment by Robbie8** [comment]
Hi,
I've read the update but I am not using a custom html module so I can't add the prepare content option as it doesn't exist in other modules - is there a way to code the prepare content feature in this plugin?

**Comment by wojsmol** [comment]
Hello
@Robbie8 Prepare content must be supported by the module in order to plugins from group content to work properly.
Regards
