### ISSUE TITLE
Issue in Joomla 3.5 (beta 2)

### ISSUE THREAD

**Issue by movieminder** [wojsmol/backbutton-plugin#6]
In the upcoming Joomla 3.5 (beta 2) version the introtext before the "read more" button disappear when the "Content - Back Button" is published in the Catogery blog view. When I change the status to "un
publish" the introtext appears correctly.

Do you have a bugfix for this problem?

**Example with plugin published:**
![with-plugin-published](https://cloud.githubusercontent.com/assets/17195859/13005189/80002508-d180-11e5-801e-3a8b6e20d362.jpg)

**Example with plugin unpublished:**
![with-plugin-unpublished](https://cloud.githubusercontent.com/assets/17195859/13005190/80031e98-d180-11e5-9783-f4fa3c62b5d6.jpg)

Thanx for your effort.
Best regards,
Movieminder

**Comment by wojsmol** [comment]
Related https://github.com/joomla/joomla-cms/issues/8024

**Comment by wojsmol** [comment]
@movieminder Please check whether the problem occurs on a Joomla! 3.5 Beta 3 - should be issued within the next 24 hours.

**Comment by movieminder** [comment]
@wojsmol Ok. I'll try it as soon as Joomla 3.5 beta 3 is available. I will let you now.

**Comment by movieminder** [comment]
@wojsmol I've installed the Joomla! 3.5 Beta 3 and it looks like the problem has been solved.
