### ISSUE TITLE
Button not displaying

### ISSUE THREAD

**Issue by Almeirim** [wojsmol/backbutton-plugin#8]
Hi

I'm using joomla 3.6.5 with one T3 framework template and I'm only managed to see the text (that works fine) without the button around. In the Plugin "Content - Back button I have set both "Wrap div" and "Add class to the link" to yes (I also tried all the possible combinations).

Can you please help me? Thanks a lot in advance.

Best regards

**Comment by wojsmol** [comment]
Hello
@Almeirim Please provide a link to the page where I can see the how back button should look.
Regards

**Comment by Almeirim** [comment]
Hello,

You can see it here http://jorge.scmscdao.pt/index.php/back-button

In the end with the text "Voltar à página anterior"

Best regards

**Comment by wojsmol** [comment]
Hallo
Please enable both options and edit https://github.com/backbutton/content-plugin/blob/master/backbutton.php#L42 to
````php
$this->params->get('linkclass') == 1 ? $aclass = 'class="button btn btn-primary"' : $aclass = '';
`````

**Comment by wojsmol** [comment]
Do you need further help?

**Comment by Almeirim** [comment]
Hi,

For the moment no. I stopped working in that project. Much obliged for your
help

2017-06-14 4:24 GMT+01:00 Wojciech Smoliński <notifications@github.com>:

**Comment by wojsmol** [comment]
I close now, you can always reopen.
