### ISSUE TITLE
Back button typo

### ISSUE THREAD

**Issue by pambesteder** [wojsmol/backbutton-plugin#9]
I have enabled the plugin .

It shows up on my page as:

BBBACK  

Huh?  So how can I fix this typo?

Pam
![typo](https://user-images.githubusercontent.com/12632086/27059335-8593d948-4f9b-11e7-91e1-66621e72a156.png)

**Comment by wojsmol** [comment]
Hello
What language is set as default for frontend and backend?

**Comment by pambesteder** [comment]
English

**Comment by wojsmol** [comment]
There is no problem on my test environment. Please check this version on your website https://github.com/backbutton/content-plugin/archive/langfix.zip

**Comment by pambesteder** [comment]
Yes that worked....thank you

**Comment by wojsmol** [comment]
Ok, in that case it will soon release a new stable version of the package.

**Comment by wojsmol** [comment]
New version of the package relased.

**Comment by pambesteder** [comment]
Thank you

**Comment by pambesteder** [comment]
Hi

I included the new version and am now getting this error at the top of my Joomla page:

Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; plgButtonBackbutton has a deprecated constructor in /home/mycusto6/public_html/beige/plugins/editors-xtd/backbutton/backbutton.php on line 19

**Comment by wojsmol** [comment]
The compatibility with php 7 will be fixed in the next release. Its release is planned for tomorrow.

**Comment by wojsmol** [comment]
dev version - https://github.com/backbutton/content-plugin/archive/php7compat.zip

**Comment by wojsmol** [comment]
New stable relese is published - see https://github.com/backbutton/packages/releases
